ROLE_WORKSTATION = "workstation"
ROLE_TEACHER = "teacher"
ROLE_MODERATOR = "moderator"
ROLE_ADMIN = "admin"
ROLE_SUPERADMIN = "superadmin"

PERMISSION_CLASSROOMS_READ_ALL = "classrooms:read:all"
PERMISSION_CLASSROOMS_READ_ASSIGNED = "classrooms:read:assigned"

PERMISSION_CLASSROOMS_MANAGE = "classrooms:manage"
PERMISSION_DEVICES_MANAGE = "devices:manage"

PERMISSION_WAN_CONTROL_ALL = "wan:control:all"
PERMISSION_WAN_CONTROL_ASSIGNED = "wan:control:assigned"

PERMISSION_USERS_MANAGE_ADMIN = "users:manage:admin"
PERMISSION_USERS_MANAGE_LOWER = "users:manage:lower"

PERMISSION_WORKSTATIONS_MANAGE = "workstations:manage"

ROLE_PERMISSIONS: dict[str, set[str]] = {
    ROLE_SUPERADMIN: {
        PERMISSION_CLASSROOMS_READ_ALL,
        PERMISSION_CLASSROOMS_MANAGE,
        PERMISSION_DEVICES_MANAGE,
        PERMISSION_WAN_CONTROL_ALL,
        PERMISSION_USERS_MANAGE_ADMIN,
        PERMISSION_USERS_MANAGE_LOWER,
        PERMISSION_WORKSTATIONS_MANAGE,
    },
    ROLE_ADMIN: {
        PERMISSION_CLASSROOMS_READ_ALL,
        PERMISSION_CLASSROOMS_MANAGE,
        PERMISSION_DEVICES_MANAGE,
        PERMISSION_WAN_CONTROL_ALL,
        PERMISSION_USERS_MANAGE_LOWER,
        PERMISSION_WORKSTATIONS_MANAGE,
    },
    ROLE_MODERATOR: {
        PERMISSION_CLASSROOMS_READ_ALL,
        PERMISSION_WAN_CONTROL_ALL,
    },
    ROLE_TEACHER: {
        PERMISSION_CLASSROOMS_READ_ASSIGNED,
        PERMISSION_WAN_CONTROL_ASSIGNED,
    },
    ROLE_WORKSTATION: {
        PERMISSION_CLASSROOMS_READ_ASSIGNED,
        PERMISSION_WAN_CONTROL_ASSIGNED,
    },
}


def get_permissions_for_role(role_name: str) -> list[str]:
    return sorted(ROLE_PERMISSIONS.get(role_name, set()))
